aliases:
  restore_cache: &restore_cache
    restore_cache:
      name: Restore Npm Package Cache
      key: dependency-cache-{{ checksum "package.json" }}

  install_node_modules: &install_node_modules
    run:
      name: Install dependencies
      command: npm install

  save_cache: &save_cache
    save_cache:
      name: Save NPM package cache
      key: dependency-cache-{{ checksum "package.json" }}
      paths:
        - ./node_modules

version: 2
jobs:
  build:
    working_directory: ~/self-organizer
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *save_cache
      - run:
          name: Run Tests
          command: npm test
